[main]
# Размер шрифта и имя
font=monospace:size=12
# Количество строк, отображаемых в выпадающем списке (1 = как у dmenu)
lines=1
# Ширина окна (в пикселях)
width=500
# Отступы вокруг окна
horizontal-pad=0
vertical-pad=0
# Внутренние отступы от краёв окна до текста
inner-pad=5
# Скругление углов (0 = прямоугольник)
border-radius=0
# Толщина рамки
border-width=1
# Приглашение (prompt) перед строкой ввода
prompt=run:
# Отключить иконки (как в dmenu)
icons-enabled=no
# Запретить изменение размера окна
resize=no
# Отображать окно в верхней части экрана (по умолчанию и так сверху, но можно явно задать)
anchor=top
# Отключить автоматический скролл
exit-on-keyboard-focus-loss=yes

[colors]
background=1d2021ff
text=d5c4a1ff
selection=91A4203f
selection-text=c4c491ff 

