# Сохранение позиции
save-position-on-quit=yes

# Языки
slang=ru,en
sid=1

# Чистые настройки через append (самые стабильные)
ytdl-raw-options-append=cookies=/home/tema/.config/yt-dlp/cookies.txt
ytdl-raw-options-append=force-ipv4=
ytdl-raw-options-append=sub-langs=ru.*,en.*
ytdl-raw-options-append=write-subs=
ytdl-raw-options-append=write-auto-subs=
ytdl-raw-options-append=embed-chapters=

# Интерфейс
osc=yes


